// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: mesh/mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message type as seen/used on the wire
	// 0 = ADAPTER_DATA (normal adapter-originated data)
	// 1 = MASTER_BEACON (mesh-internal heartbeat from master)
	// 3 = SERIAL_CMD_BROADCAST (special: server→device serial command to broadcast adapter data)
	MessageType uint32 `protobuf:"varint,1,opt,name=messageType,proto3" json:"messageType,omitempty"`
	// Adapter data type (maps to firmware enum adapter_types)
	//
	//	-1 UNKNOWN
	//	 0 PIR
	//	 1 WIFI (reserved)
	//	 2 LED  (reserved)
	//	 3 SERIAL (serial control / health / commands)
	DataType int32 `protobuf:"zigzag32,2,opt,name=dataType,proto3" json:"dataType,omitempty"` // zigzag encoded
	// MAC addresses (6 bytes used). The server only needs to send targetMacAddress.
	// originMacAddress, lastHopMacAddress, and hopCount are automatically generated by the device.
	OriginMacAddress  []byte `protobuf:"bytes,3,opt,name=originMacAddress,proto3" json:"originMacAddress,omitempty"`   // 6 bytes (auto-generated by device)
	TargetMacAddress  []byte `protobuf:"bytes,4,opt,name=targetMacAddress,proto3" json:"targetMacAddress,omitempty"`   // 6 bytes (required from server)
	LastHopMacAddress []byte `protobuf:"bytes,5,opt,name=lastHopMacAddress,proto3" json:"lastHopMacAddress,omitempty"` // 6 bytes (auto-generated by device)
	// 12-byte adapter payload. For SERIAL (dataType=3) this contains control opcodes.
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // up to 12 bytes used
	// Mesh hop count (0 for locally originated)
	HopCount      uint32 `protobuf:"varint,7,opt,name=hopCount,proto3" json:"hopCount,omitempty"` // auto-generated by device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshMessage) Reset() {
	*x = MeshMessage{}
	mi := &file_mesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshMessage) ProtoMessage() {}

func (x *MeshMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshMessage.ProtoReflect.Descriptor instead.
func (*MeshMessage) Descriptor() ([]byte, []int) {
	return file_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *MeshMessage) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MeshMessage) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *MeshMessage) GetOriginMacAddress() []byte {
	if x != nil {
		return x.OriginMacAddress
	}
	return nil
}

func (x *MeshMessage) GetTargetMacAddress() []byte {
	if x != nil {
		return x.TargetMacAddress
	}
	return nil
}

func (x *MeshMessage) GetLastHopMacAddress() []byte {
	if x != nil {
		return x.LastHopMacAddress
	}
	return nil
}

func (x *MeshMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MeshMessage) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

var File_mesh_mesh_proto protoreflect.FileDescriptor

const file_mesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x0fmesh/mesh.proto\x12\x04mesh\"\x81\x02\n" +
	"\vMeshMessage\x12 \n" +
	"\vmessageType\x18\x01 \x01(\rR\vmessageType\x12\x1a\n" +
	"\bdataType\x18\x02 \x01(\x11R\bdataType\x12*\n" +
	"\x10originMacAddress\x18\x03 \x01(\fR\x10originMacAddress\x12*\n" +
	"\x10targetMacAddress\x18\x04 \x01(\fR\x10targetMacAddress\x12,\n" +
	"\x11lastHopMacAddress\x18\x05 \x01(\fR\x11lastHopMacAddress\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1a\n" +
	"\bhopCount\x18\a \x01(\rR\bhopCountB,Z*github.com/superbrobenji/motionServer/meshb\x06proto3"

var (
	file_mesh_mesh_proto_rawDescOnce sync.Once
	file_mesh_mesh_proto_rawDescData []byte
)

func file_mesh_mesh_proto_rawDescGZIP() []byte {
	file_mesh_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_mesh_proto_rawDesc), len(file_mesh_mesh_proto_rawDesc)))
	})
	return file_mesh_mesh_proto_rawDescData
}

var file_mesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mesh_mesh_proto_goTypes = []any{
	(*MeshMessage)(nil), // 0: mesh.MeshMessage
}
var file_mesh_mesh_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_mesh_proto_init() }
func file_mesh_mesh_proto_init() {
	if File_mesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_mesh_proto_rawDesc), len(file_mesh_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_mesh_proto_depIdxs,
		MessageInfos:      file_mesh_mesh_proto_msgTypes,
	}.Build()
	File_mesh_mesh_proto = out.File
	file_mesh_mesh_proto_goTypes = nil
	file_mesh_mesh_proto_depIdxs = nil
}
